### ISSUE TITLE
[game-request] The Chronicles of Riddick: Assault on Dark Athena

### ISSUE THREAD

**Issue by asior1985** [anzz1/openspy-client#1]
### Game name

The Chronicles of Riddick: Assault on Dark Athena

### Game version

1.0.0.1

### Game release

CD / DVD

**Comment by anzz1** [comment]
I am having a hard time to find any information about this game, as if it were swallowed by the void of internet. Did this game ever even use GameSpy Arcade as its' online service, as I cannot find any reference to that? Then again, I can't find any information that it didn't, either.

If you have any resources to point towards information of this game's multiplayer capabilities, that would be appreciated, as currently I have nothing to go by.

**Comment by anzz1** [comment]
What initially confused me is that looking through the files of the GameSpy Arcade client, this game can be found there referred to as "coraoda". But other mentions were nowhere to be found.

Digging into the game code after unpacking its' DRM scheme (TAGES SolidShield) revealed that this game indeed is not using GameSpy, but another similar now defunct middleware called [Quazal Net-Z / Rendes-Vous](https://www.gamedeveloper.com/pc/quazal-releases-net-z-4-3-and-rendez-vous-2-0).

After the fact, I also found that this information could have been easily obtained from the [game's manual](https://oldgamesdownload.com/wp-content/uploads/The_Chronicles_of_Riddick_Assault_on_Dark_Athena_Manual_Win_EN.pdf).  
In the Credits section, it clearly states:
> Multiplayer Connectivity by Quazal.

So unfortunately this game cannot be supported by OpenSpy, as it never used GameSpy in the first place.
