### ISSUE TITLE
[game-request] Rise of Nations - Rise of Legends

### ISSUE THREAD

**Issue by Ston3Cold** [anzz1/openspy-client#2]
### Game name

Rise of Nations - Rise of Legends

### Game version

0.0704.1001.0000.13.0

### Game release

CD / DVD

### Additional information

The game tries to communicate with a patch server which no longer exists and forces the game not to progress / continue to the online menu or lobby. The game exe will most likely require modification to bypass the patch server, so I'm hoping that the game can be supported.

**Comment by anzz1** [comment]
Here is a WIP beta version if you want to test it, I managed to get past the check and create a lobby but didn't actually try to play a match.

It's crude and very much WIP though, the login/logout takes a good 30 seconds to complete and you might get the "Program is not responding" looking like it crashed. This is normal however, and you need to press "Wait for program to respond" and wait. This is because not all the checks are properly patched yet and it proceeds after the timeout.

[rof_wip_beta_v1.zip](https://github.com/anzz1/openspy-client/files/12568366/rof_wip_beta_v1.zip)

**Comment by Ston3Cold** [comment]
Amazing, thanks a lot! Will give this a try and give feedback asap :D

**Comment by anzz1** [comment]
Here's another beta version which brings down the initial connection delay from 30+ seconds to much more reasonable ~5 seconds.

[rof_wip_beta_v2.zip](https://github.com/anzz1/openspy-client/files/12640553/rof_wip_beta_v2.zip)

**Comment by Ston3Cold** [comment]
I have tried beta 2 and 3 and man does it load quick - it brings me to an account creation and login screen. I did create an account using account.openspy.net - but it doesn't seem to utilize the account I already created with either of the two nicknames somehow. Using something such as "cports" I already have forwarded UDP port 6112 which the game seems to use, but that doesn't help. Not sure if its trying to do anything else in the background, but at least we're one step closer to the online lobby screen , we just need to be able to create and login to an account :)

**Comment by anzz1** [comment]
Okay the "beta 2" version is probably close to what will be released, the client-side of things seems to work correctly so far but there is some server-side stuff to fix still. Even now it is possible though to get into the game by being fast and juking the crashes clicking "Ignore" to any assertions that pop up. The game itself should work fine, as the errors are related to the chat/lobby functionality.

The game does indeed have a option to "create account", but what it actually does is create a "profile" which is not linked to any particular account. I don't think it matters though, but if you want to create a profile which is linked to a account you can do it following these steps:
1. Create (or log into) an account at http://account.openspy.net
2. Go to "Manage Profiles" -> "New Profile"
3. Enter the nick you want twice in both "Nick" and "UniqueNick" fields, and set the Namespace ID to 18.
4. In game choose existing account and use the nick and password you chose in earlier steps.

**Comment by anzz1** [comment]
This game is now supported.
