### ISSUE TITLE
[bug] I can see the servers, but I can't connect

### ISSUE THREAD

**Issue by Bam449** [anzz1/openspy-client#4]
### Game name

Need For Speed Hot Pursuit 2

### 🔍

- [X] The game is in the [supported games list](https://github.com/anzz1/openspy-test#working-games).

### What happened?

Hello. I'm starting the game. I can see all the servers, but I can't connect for the reason "Connect attempt failed. Please check ur connection and try again".  I copied the file dsound.dll to the game folder. I also tried the method via wsfix and added the dsound.asi file. Then I changed gamespy.com on openspy.net in the .exe file of the game using the hex editor. Then I asked my friends from Germany, Russia and Moldova to test it. Everyone has the same mistake.
Nothing helped. But when I changed gamespy.com on openspy.org then I was able to connect to the server and was able to play. I do not know what the error is, but it seems to me it is related to domains openspy.net and openspy.org .

### Game version

242

### Game release

CD / DVD

### OpenSpy DLL Name

dsound.dll

### OpenSpy DLL Version

1.0.69 and all

### Additional game information

I used the clean version 242. And also installed wsfix (ASI loader)

**Comment by Bam449** [comment]
The problem is the encryption in the 242 version of the game. If your exe file is not the same as the server, then you cannot connect to the server. If you use dsound.dll , but the exe file is fixed on the server via the hex editor, then you will not connect to the server. You also cannot connect to the server if the server uses openspy.org , and the client uses openspy.net since the exe files are different.

**Comment by anzz1** [comment]
Right, there must be a integrity check somewhere which fails if the game files are modified.

The check could be patched, but for now the simplest thing to do is simply for all players to use the same unmodified game files.
Or rather, the same NoCD patch since the SafeDisc DRM can cause problems.
One is linked in the [supported games list](https://github.com/anzz1/openspy-test#supported-games-list)
